### ISSUE TITLE
Add NOTICE files to each repository

### ISSUE THREAD

**Issue by kenji-miyake** [autowarefoundation/autoware#90]
I'll change the name and year from https://github.com/autowarefoundation/autoware/blob/main/NOTICE depending on the repository's files.

- [x] autoware_common
- [x] autoware.core
- [x] autoware.universe
- [x] autoware_launch
- [x] sample_sensor_kit_launch
- [x] sample_vehicle_launch
- [x] autoware_individual_params
- [x] autoware-github-actions
- [x] autoware-documentation

---

FYI, to clone these repositories:

```yaml
repositories:
  autoware:
    type: git
    url: https://github.com/autowarefoundation/autoware.git
    version: main
  autoware_common:
    type: git
    url: https://github.com/autowarefoundation/autoware_common.git
    version: main
  autoware.core:
    type: git
    url: https://github.com/autowarefoundation/autoware.core.git
    version: main
  autoware.universe:
    type: git
    url: https://github.com/autowarefoundation/autoware.universe.git
    version: main
  autoware_launch:
    type: git
    url: https://github.com/autowarefoundation/autoware_launch.git
    version: main
  sample_sensor_kit_launch:
    type: git
    url: https://github.com/autowarefoundation/sample_sensor_kit_launch.git
    version: main
  sample_vehicle_launch:
    type: git
    url: https://github.com/autowarefoundation/sample_vehicle_launch.git
    version: main
  autoware_individual_params:
    type: git
    url: https://github.com/autowarefoundation/autoware_individual_params.git
    version: main
  autoware-github-actions:
    type: git
    url: https://github.com/autowarefoundation/autoware-github-actions.git
    version: main
  autoware-documentation:
    type: git
    url: https://github.com/autowarefoundation/autoware-documentation.git
    version: main
```
